version: '3.5'

services:
  laravel:
    build:
      context: ./projects/laravel
    container_name: laravel
    restart: always
    ports:
      - "${HTTP_WEBSERVER_PORT}:80"
      - "${HTTPS_WEBSERVER_PORT}:443"
    links:
      - postgresql
      - redis
      - mailcatcher
    volumes:
      - ${LARAVEL_DOCUMENT_ROOT-./projects/laravel}:/var/www/html
      - ${PHP_INI-./docker/config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./docker/config/vhosts}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR-./docker/logs/apache2}:/var/log/apache2
  postgresql:
    build:
      context: ./docker/bin/postgresql
    container_name: postgresql-15.2
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA_DIR-./docker/data/postgresql}:/var/lib/postgresql/data
      - ${POSTGRES_LOG_DIR-./docker/logs/postgresql}:/logs
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
  redis:
    build:
      context: ./docker/bin/redis
    container_name: redis-1.0.0
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${REDIS_DATA_DIR-./docker/data/redis}:/data
      - ${REDIS_LOG_DIR-./docker/logs/redis}:/var/log/redis
      - ${REDIS_CONF-./docker/config/redis/redis.conf}:/usr/local/etc/redis/redis.conf
  mailcatcher:
    restart: always
    image: dockage/mailcatcher:0.8.2
    container_name: mailcatcher-0.8.2
    ports:
    - "${MAILCATCHER_PORT}:1080"
    - "${MAILCATCHER_PORT_CLIENT}:1025"